export const environment = {
  production: true,
  AUTH_COOKIE_NAME : 'TAXBLOCKAUTH',
  DOMAIN : "taxblock.in",
  // WebsiteURL:'https://taxblock.in',
  // CLIENT_APP_URL:'https://client.taxblock.in/',
  // CRM_APP_URL:'https://crm.taxblock.in/',
  // TAXATION_APP_URL:'https://itax.taxblock.in/',
  // DIY_APP_URL:'https://diy.taxblock.in/',
  // BASE_API_URL: 'https://apigateway.taxblock.in/api',
  // PAYTMURL: 'https://securegw.paytm.in/order/process',
  // EFilling_API_URL: "https://efilingnew.taxblock.in",
  WebsiteURL: "https://poi.taxblock.in/",
	CLIENT_APP_URL: "http://clientuat.taxblock.in/",
	CRM_APP_URL: "http://crmuat.taxblock.in/",
	TAXATION_APP_URL:'http://newpoiuat.taxblock.in/',
	BASE_API_URL: "https://apipoi.taxblock.in/api/",
};